### ISSUE TITLE
Problem when run in iOS8.2 by iPhone6

### ISSUE THREAD

**Issue by lelang** [Yalantis/GuillotineMenu#17]
Using Xcode 7.2 + swift2.0
Thank you for your menu, it's so cool
But when i try it in iPhone6 using iOS8.2, it have big problem.
Just display :
VC: viewWillAppear
VC: viewDidAppear
Menu: viewWillAppear
VC: viewWillDisappear
willStartPresentation
![img_0221](https://cloud.githubusercontent.com/assets/15363212/12528276/e6ff0ea4-c1c2-11e5-97ba-a10eba8a0603.jpg)

**Comment by EgorSobko** [comment]
@lelang Thanks for interest to this menu, please, try a new 2.0.0 version of menu, if you have problems, do not hesitate to contact us again

**Comment by lelang** [comment]
@EgorSobko  Thanks for feedback me, when try a new 2.0.0 example, i still have same problem when i run on iOS 8.2 iPhone6 (in Xcode i just change the The deployment target to 8.0 instead 8.3 default).
just display in debug screen when i tap on bar button
VC: viewWillAppear
VC: viewDidAppear
Menu: viewWillAppear
VC: viewWillDisappear
willStartPresentation

**Comment by mrcompoteee** [comment]
@lelang Thank for using the Guillotine menu. We fixed this issue in the latest version (2.0.1) and now it's comptaible with iOS 8.0+

Feel free to use it!

**Comment by Saulenco** [comment]
this issue still persist on the last version if for MenuViewController you use an extension of a UITableViewController
